# Generated by Django 2.2.5 on 2020-02-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('start_line', models.PositiveIntegerField()),
                ('end_line', models.PositiveIntegerField()),
                ('create_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MethodDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('sig', models.CharField(max_length=255)),
                ('create_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('slice_dir', models.CharField(max_length=255)),
                ('label_dir', models.CharField(max_length=255)),
                ('embedding_dim', models.PositiveIntegerField()),
                ('hidden_dim', models.PositiveIntegerField()),
                ('word_freq_gt', models.PositiveIntegerField()),
                ('early_stop_patience', models.PositiveIntegerField()),
                ('base_learning_rate', models.FloatField()),
                ('batch_size', models.PositiveIntegerField()),
                ('epoch', models.PositiveIntegerField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaintFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255, unique=True)),
                ('slice_file', models.CharField(max_length=255)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ml_app.MethodDescription')),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ml_app.Location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_dict_path', models.CharField(max_length=255)),
                ('model_path', models.CharField(max_length=255)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_app.ModelConfig')),
            ],
        ),
        migrations.AddField(
            model_name='methoddescription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_app.Project'),
        ),
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_app.Project'),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe', models.BooleanField(default=False)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('taint_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ml_app.TaintFlow')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='methoddescription',
            unique_together={('clazz', 'method', 'sig', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('source_file', 'start_line', 'end_line', 'project')},
        ),
    ]
