# Generated by Django 2.2.5 on 2020-02-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0002_auto_20200211_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='accurate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='f1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='precision',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='recall',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
