# Generated by Django 2.2.5 on 2020-02-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0003_auto_20200211_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='train_percent',
            field=models.FloatField(default=1),
        ),
    ]
